fix: misleading error when paymaster policy check fails
bcnmy/biconomy-client-sdk pull request #335
Opened 2023-12-05 13:10 UTC by livingrockrises

use undefined in place of ! + check on limits returned by paymaster and throw

# Summary

Related Issue: # (issue number)

## Change Type

- [ ] Bug Fix
- [ ] Refactor
- [ ] New Feature
- [ ] Breaking Change
- [ ] Documentation Update
- [ ] Performance Improvement
- [ ] Other

# Checklist

- [ ] My code follows this project's style guidelines
- [ ] I've reviewed my own code
- [ ] I've added comments for any hard-to-understand areas
- [ ] I've updated the documentation if necessary
- [ ] My changes generate no new warnings
- [ ] I've added tests that prove my fix is effective or my feature works
- [ ] All unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published

# Additional Information

# Branch Naming

2023-12-08 11:26 UTC, VGabriel45 commented on packages/account/src/BiconomySmartAccount.ts
>            throw new Error("Userop callData cannot be undefined");
Here you can also use the checkNullOrUndefined() helper method

2023-12-08 11:28 UTC, VGabriel45 requested changes
All seems good except some places where the helper method can be used instead of manual checking and also there are some linter issues

2023-12-08 11:30 UTC, livingrockrises commented on packages/account/src/BiconomySmartAccountV2.ts
> +        if (userOp.callData === undefined || userOp.callData === null) {
I tried doing that but the build fails because below code doesn't get the context if it's checked for undefined already

2023-12-08 12:00 UTC, livingrockrises commented on packages/account/src/SmartAccount.ts
> +        if (userOp.maxFeePerGas === undefined || userOp.maxPriorityFeePerGas === undefined) {
fixed

2023-12-11 08:27 UTC, AmanRaj1608 approved these changes

2023-12-11 10:03 UTC, merged