Feat/devx 405 abstract chain
bcnmy/biconomy-client-sdk pull request #343
Opened 2023-12-27 11:32 UTC by VGabriel45

# Summary

The scope of this PR is to abstract away the need to provide a chain id manually, we can extract the chain id from bundler url as bundler is now required.

Related Issue: #DEVX-405

## Change Type

- [ ] Bug Fix
- [x] Refactor
- [x] New Feature
- [ ] Breaking Change
- [ ] Documentation Update
- [ ] Performance Improvement
- [ ] Other

# Checklist

- [x] My code follows this project's style guidelines
- [x] I've reviewed my own code
- [ ] I've added comments for any hard-to-understand areas
- [ ] I've updated the documentation if necessary
- [x] My changes generate no new warnings
- [x] I've added tests that prove my fix is effective or my feature works
- [x] All unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published

2023-12-27 11:35 UTC, VGabriel45 commented
The PR also contains latest "develop" branch updates

2024-01-02 09:42 UTC, joepegler commented
Hmmm, I like this but I think I'd prefer to set the bundlerUrl (to our own bundler) only if the chainId is missing. So the chainId becomes mandatory if the bunderlUrl is missing, as the only dynamic part of our bundlerUrl is the chainId. 

I think removing the chainId from the config entirely could cause confusion as it's a param I'd expect to see. 

TLDR: Inferring the bunderUrl from the chainId would make more sense than inferring the chainId from the bundlerUrl.

2024-01-06 08:49 UTC, AmanRaj1608 commented on packages/account/src/BaseSmartAccount.ts
We don't need this in v4

2024-01-06 08:50 UTC, AmanRaj1608 requested changes
Do take a back merge from v4

2024-01-12 10:45 UTC, livingrockrises commented
resolve conflicts

2024-01-15 16:21 UTC, closed without merging