Feat: Add Logger
bcnmy/biconomy-client-sdk pull request #353
Opened 2024-01-05 13:09 UTC by AmanRaj1608

Instead of adding a new package for adding logger in all packages, let's reuse the Logger class.

2024-01-05 13:54 UTC, joepegler requested changes

2024-01-05 13:54 UTC, joepegler commented on packages/account/src/BiconomySmartAccountV2.ts
> +    if (!biconomySmartAccountConfig?.defaultValidationModule) {
My logic was slightly off here.

```
if (!config?.defaultValidationModule) {
  const newModule = await ECDSAOwnershipValidationModule.create({
    signer: biconomySmartAccountConfig.signer!,
  });
  config.defaultValidationModule = newModule;
}
config.activeValidationModule = config?.activeValidationModule ?? config.defaultValidationModule;

return new BiconomySmartAccountV2(config);
```

2024-01-05 14:32 UTC, AmanRaj1608 commented on packages/account/src/BiconomySmartAccountV2.ts
> +    if (!biconomySmartAccountConfig?.defaultValidationModule) {
Yeah makes sense, updated the code

2024-01-05 15:51 UTC, joepegler approved these changes

2024-01-05 16:05 UTC, joepegler requested changes
You'll also need to set it in the constructor the same way you do the others: 

```    this.defaultValidationModule = biconomySmartAccountConfig.defaultValidationModule;
    this.activeValidationModule = biconomySmartAccountConfig.activeValidationModule;

```

2024-01-09 11:49 UTC, joepegler approved these changes

2024-01-09 11:54 UTC, VGabriel45 commented
Can we have the Logger class just in one place and use it from there instead of adding it in every module where we need it ?

2024-01-09 12:13 UTC, AmanRaj1608 commented
@VGabriel45 This was there previously in `common` package. Adding this will introduce again another package which we need to deploy. If we have it in one package and import in another it can introduce circular dependecies
account importing paymaster for paymaster class and paymaster importing account for common package.

So solution I think of
- Use an external logger class and add as dependency in all class
- Re-use code but this is much lighter than any package and does the job

2024-01-09 13:19 UTC, VGabriel45 approved these changes

2024-01-09 13:22 UTC, merged