rpcUrl as required and removed redundant code
bcnmy/biconomy-client-sdk pull request #430
Opened 2024-02-21 16:56 UTC by VGabriel45

# Summary

In order to fix current and potential new issues when using third party providers like Privy or Particle Auth we will refactor rpcUrl as required field on smart account class instance.

Related Issue: # (issue number)

## Change Type

- [x] Bug Fix
- [x] Refactor
- [ ] New Feature
- [x] Breaking Change
- [x] Documentation Update
- [ ] Performance Improvement
- [ ] Other

# Checklist

- [x] My code follows this project's style guidelines
- [x] I've reviewed my own code
- [x] I've added comments for any hard-to-understand areas
- [ ] I've updated the documentation if necessary
- [x] My changes generate no new warnings
- [x] I've added tests that prove my fix is effective or my feature works
- [x] All unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published

2024-02-21 17:23 UTC, joepegler commented
As discussed we should keep the chainId from the signer and compare it with the chainId from the bundler

2024-02-21 17:24 UTC, joepegler requested changes

2024-02-22 08:48 UTC, VGabriel45 commented on packages/account/tests/account.e2e.spec.ts
> +      rpcUrl: mumbai.viemChain.rpcUrls.default.http[0],
Ok not sure what's the issue here ? Should not use viemChain instead of mumbai.viemChain ?

2024-02-22 10:02 UTC, joepegler commented
I think you can move the failing unit tests into the e2e tests

2024-02-25 23:42 UTC, livingrockrises commented
resolve conflicts

2024-02-25 23:42 UTC, livingrockrises approved these changes

2024-02-26 11:03 UTC, joepegler approved these changes

2024-02-26 13:41 UTC, merged